FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore ./src/Orchestrator.Service/Orchestrator.Service.csproj
RUN dotnet publish ./src/Orchestrator.Service/Orchestrator.Service.csproj -c Release -o /out

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /out .
EXPOSE 8080
ENTRYPOINT ["dotnet", "Orchestrator.Service.dll"]
